### ISSUE TITLE
using loop leads to "jumps" between last and first slide

### ISSUE THREAD

**Issue by gre** [gre/diaporama#27]
filed by @AVVS : https://github.com/glslio/diaporama/issues/1 (old repository)

**Comment by gre** [comment]
should be fixed in `diaporama@1.3.0` & `diaporama-react@1.5.0` cc @AVVS

**Comment by AVVS** [comment]
I've tested new release and it works pretty well, except for one edge-case. When using it in combination with `.next(1000)` from the previous release (probably `.prev` would act the same form last to first slide), time speedup only persists on the part of the original loop, and when extra step that you've added for the loop transition kicks in, `time` is back to it's standard 1x flow

It's not that big of an issue compared to what it had been before (no transition or a jump when there is a transition), but you can see the inconsistency

**Comment by gre** [comment]
good catch

**Comment by gre** [comment]
released `diaporama@1.4.0` and `diaporama-react@1.6.0`  (that's a new minor because `duration` semantic slightly changed, the last transition time is counted in duration when loop is true)
