### ISSUE TITLE
Black "blink" during initialization of the slideshow

### ISSUE THREAD

**Issue by gre** [gre/diaporama#28]
filed by @AVVS : https://github.com/glslio/diaporama/issues/2 (old repository)

**Comment by AVVS** [comment]
I've finally had a chance to try proposed solutions and nothing seemed to work properly. If it's a placeholder image that's rendered outside diaporama - then it's a problem to crop it the same way as diaporama does, and then, it's still tricky to turn placeholder off in the right moment - eye catches this transition. Would be nice to have the placeholder option "natively"

**Comment by gre** [comment]
I will address that ASAP

**Comment by gre** [comment]
Hi @AVVS,

I have fixed diaporama in order to make it render the first frame as soon as the first image is loaded. I guess I can't do better than that and you can still do something else before `"canplay"` is triggered (canplay means the first image is loaded basically).

I guess you don't have to load the first image yourself anymore and to illustrate that I've created an example:

https://github.com/gre/diaporama-react-load-test/blob/master/index.js
that is self hosted here: http://greweb.me/diaporama-react-load-test

This example shows the moment where the 4 events are triggered.
Let's only focus on **the second example using `"canplay"`**: it seems to properly display the placeholder first image as soon as it is loaded without a *Black "blink"*.

**Comment by gre** [comment]
is the issue fixed? thanks

**Comment by AVVS** [comment]
I think it is, at least in the test suite you've prepared. Is this code merged into master right now?

**Comment by gre** [comment]
yes it is

**Comment by gre** [comment]
I think this is fixed now,
http://greweb.me/diaporama-react-load-test shows ways to fix it.
