### ISSUE TITLE
Find ways to only use one webgl canvas

### ISSUE THREAD

**Issue by gre** [gre/diaporama#34]
The use of `KenBurns.WebGL` and `glsl-transition-core` force to use different canvases (3) to perform the diaporama. This doesn't scale because WebGL have limited simultaneous contexts.

We should probably use `framebuffer`s instead.

**Comment by gre** [comment]
WIP using http://stack.gl/packages/#stackgl/gl-fbo

**Comment by AVVS** [comment]
let me know when its ready - would be glad to test it

**Comment by gre** [comment]
sure :-) It might take me days but the effort worth it I think, the current implement relying on different canvases sucks and using one same WebGL context might improve perfs alot.

**Comment by gre** [comment]
work in great progress in branch `refactoring/fbo`.

on Chrome / Macbook Pro (2,6 GHz Intel Core i7): benchmark is showing **performance improvement from 52 FPS to 58 FPS** on a `2048 x 1024` canvas using images with various dimensions (from `600 x 400` to `3600 x 2700`).
Besides the performance, the second advantage is that there is now only one `webgl` context which allows to create more diaporama (because we can't have so much simultaneous canvas running webgl, there is a limit where the browser will start destroying contexts).

I still need to polish things and have not implemented yet the `canvas2d` support.

**Comment by gre** [comment]
released **`v1.5.0`** ready to be tested
