### ISSUE TITLE
slide and slideEnd trigger twice when loop:true at last slide

### ISSUE THREAD

**Issue by gre** [gre/diaporama#48]
from @senntyou in https://github.com/gre/diaporama/issues/47#issuecomment-125629168

> Additionally, i found a bug of diaporama. When diaporama is about to circulate, "slide" and "slideEnd" will be triggered twice.
```
diaporama.addListener('slide', function() {console.log('slide')});
diaporama.addListener('slideEnd', function() {console.log('slideEnd')});
diaporama.addListener('transition', function() {console.log('transition')});
diaporama.addListener('transitionEnd', function() {console.log('transitionEnd')});
```
![image](https://cloud.githubusercontent.com/assets/12265053/8934109/a053af2c-3578-11e5-9aec-fad4c6ba630c.png)

**Comment by senntyou** [comment]
so glad for communication with great master, @gre , thank you for your hard work.
